Update README.md
neilpower/hermes pull request #5
Opened 2020-07-03 18:01 UTC by neilpower-test

2020-07-03 18:21 UTC, neilpower requested changes
not changes we want

2020-07-03 18:22 UTC, neilpower-test commented
!hermes unapproved

2020-07-08 18:28 UTC, neilpower-test commented
!hermes rejected

2020-07-08 18:28 UTC, neilpower-test commented
!hermes rejected

2020-07-21 22:13 UTC, closed without merging